name: CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Update packages
      run: sudo apt-get update

    - name: Setup dependencies
      run: sudo apt-get install --fix-missing libgl1-mesa-dev libglew-dev libglfw3-dev libxkbcommon-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build 
